name: Release

on:
  push:
    tags: "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      # this is from a fork/PR to add Swift 6.1 support, pinning commit so nothing unexpected happens
      # should update this once 6.1 gets merged into the actual action though
      - uses: swift-actions/setup-swift@c3d14e82ba68208eb830b63e91d6b806467a09b5
        with:
          swift-version: 6.1
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4
      - name: Build
        run: just build
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{matrix.os}}
          path: .build/release/Ticketmeister
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # we need build to be complete before doing this
    needs: [build]
    steps:
      - name: Retrieve binaries
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: binary-*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./artifacts/*
          fail_on_unmatched_files: true
