name: Swift

on:
  push:
    branches: ["main"]
    paths: ["**.swift"]
  pull_request:
    branches: ["main"]
    paths: ["**.swift"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # this is from a fork/PR to add Swift 6.1 support, pinning commit so nothing unexpected happens
      # should update this once 6.1 gets merged into the actual action though
      - uses: swift-actions/setup-swift@c3d14e82ba68208eb830b63e91d6b806467a09b5
        with:
          swift-version: 6.1
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
# we don't test "Yet" lmao
#    - name: Run tests
#      run: swift test -v
