name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build (Swift ${{matrix.swift}} on ${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.1", "6.1"]

    steps:
    - uses: swift-actions/setup-swift@v2.2.0
      with:
        swift-version: ${{matrix.swift}}
    - uses: extractions/setup-just@v3
      with:
        just-version: 1.40.0
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
# we don't test "Yet" lmao
#    - name: Run tests
#      run: swift test -v
